ServerName localhost

SetEnvIf X-Forwarded-Proto "^https$" HTTPS=on

<Directory /var/www/html/public>
    Options FollowSymLinks
    AllowOverride None
    Require all granted
    DirectoryIndex index.php
    FallbackResource /index.php
</Directory>
